evepoker/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
admin.autodiscover()

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^help/', views.help, name='help'),
    url(r'^users/', include('users.urls')),
    url(r'^tables/', include('tables.urls')),
    url(r'^admin/', admin.site.urls),
]

tables/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^(?P<tableID>\d+)/$', views.joinTable),
    url(r'^$', views.tables),
    url(r'^newtable', views.newtable),
    url(r'^leavetable/$', views.leaveTable),
]

users/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.profile, name='profile'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^oauth$', views.oauth, name='oauth'),
]

tables/models.py
from django.db import models
from django import forms

# Table Model
class Table(models.Model):
	public = models.BooleanField(default=True)
	password = models.CharField(max_length=16, default="")
	name = models.CharField(max_length=32)
	currentUsers = models.IntegerField()
	tableLimit = models.FloatField()
	tableBlind = models.FloatField()
	
	def __unicode__(self):
		return self.tableType
	
	# set number of users
	def changeUsers(self, change):
		newVal = currentUsers + change
		
		# don' change max size
		if (newVal > 10 or newVal < 1):
			return -1
		else:
			self.currentUsers = newVal
			self.save()
		return newVal
		
	# close table functions
	def closeTable(self):
		self.currentUsers = 0
		return

# Form for creating new talbles
class NewTableForm(forms.Form):
	public = forms.BooleanField()
	#password = forms.CharField(max_length=16)
	tableLimit = forms.FloatField()
	tableBlind = forms.FloatField()
	name = forms.CharField(max_length=32)

users/models.py
from django.db import models
from django.contrib.auth.models import User # to extend the basic user

class User(models.Model):
	character_name = models.TextField()
	character_id = models.IntegerField()
	user_stats =  models.OneToOneField('UserStats', on_delete=models.CASCADE)

	# Override unicode method
	def __unicode__(self):
		return self.character_name

	def getInfo(self):
		return {
			"username": self.character_name,
			"userstats": self.user_stats.getInfo()
		}


class UserStats(models.Model):
	balance = models.FloatField()
		
	def changeBalance(self, change):
		newVal = self.balance + change
		if (newVal <= 0):
			newVal = 0
		self.balance = newVal
		self.save()
		return newVal

	def getInfo(self):
		return {
			"balance": "{:,}".format(self.balance)
		}
			

users/forms.py
from .models import UserStats
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username',)

evepoker/views.py
from django.shortcuts import render_to_response, render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.template import RequestContext
from esi.esi import esi_secure_url, esi_update_token, esi_verify
from esipy.exceptions import APIException
from django.views.generic import TemplateView
from users.views import userCleanSession

def home(request):
	args = {}
	if 'token' in request.session :
		try:
			esi_update_token(request)
		except APIException as err:
			print (err)
			args['esi'] = esi_secure_url
			userCleanSession(request)
			return render(request, 'index.html', args)
		try:
			verify = esi_verify()
		except:
			args['esi'] = esi_secure_url
			userCleanSession(request)
			return render(request, 'index.html', args)

		request.session['char'] = verify
		return render(request, 'index.html', args)
	else:
		args['esi'] = esi_secure_url
		userCleanSession(request)
		return render(request, 'index.html', args)
	
def help(request):
	args = {}
	return render(request, 'help.html', args)
	

tables/views.py
from django.shortcuts import render_to_response, render, redirect
from django.http import HttpResponse
from .models import Table, NewTableForm
from django.contrib.auth import authenticate, login
from django.template import RequestContext
from users.models import User, UserStats
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from decorators import esi_login_required

# display tables on home page
@esi_login_required
def tables(request):
	args = {}
	table_list = Table.objects.all()
	page = request.GET.get('page', 1)

	paginator = Paginator(table_list, 2)
	try:
		args['tables'] = paginator.page(page)
	except PageNotAnInteger:
		args['tables'] = paginator.page(1)
	except EmptyPage:
		args['tables'] = paginator.page(paginator.num_pages)

	return render(request, 'tables.html', args)

# Leave table REST interface
@csrf_exempt
def leaveTable(request):
	args = {}
	if request.method == 'POST':
	
		# Parse POST variables
		userid = request.POST['userid'];
		tableid = request.POST['tableid'];
		pot = request.POST['pot'];
		
		"""
		#update user balance
		user = UserStats.objects.get(user=userid)
		user.balance = user.balance+float(pot)
		user.save()
		"""
		
		#Change number of tables
		table = Table.objects.get(id=tableid)
		table.currentUsers = table.currentUsers-1
		table.save()
	return HttpResponse('UPDATED',status=200)
	
# join a table
@esi_login_required
def joinTable(request, tableID=1):
		
	#Update number of users
	table = Table.objects.get(id=tableID)
	table.currentUsers = table.currentUsers +1
	table.save()

	args = RequestContext(request)
	args['tables'] = table

	# Add User
	current_user = User.objects.get(character_id=request.session['char']['CharacterID'])
	current_user_stats = current_user.user_stats

	args['table'] = table.id
	args['username'] = current_user.character_name
	args['id'] = current_user.character_id
	args['tableLimit'] = table.tableLimit
	args['tableBlind'] = table.tableBlind
	args['tableName'] = table.name
	args['tablePublic'] = table.public
	
	## Inject amount of player $$ into game
	args['amountPlay'] = table.tableBlind*25
	current_user_stats.changeBalance(table.tableBlind*25)

	request.session['userinfo']['userstats'] = current_user_stats.getInfo()
	
	return render_to_response('game.html', args)


@esi_login_required
def newtable(request):
	if request.method == 'POST': # If the form has been submitted...
		# ContactForm was defined in the the previous section
		form = NewTableForm(request.POST) # A form bound to the POST data
		print (form.is_valid())
		print (form)
		if form.is_valid(): # All validation rules pass
			# Process the data in form.cleaned_data
			# ...

			newTableEntry = Table(currentUsers=1, public=form.cleaned_data['public'], tableLimit=form.cleaned_data['tableLimit'], tableBlind=form.cleaned_data['tableBlind'], name=form.cleaned_data['name'] )
			newTableEntry.save()
			args = RequestContext(request)
			
			args['user'] = User(character_id=request.session['char']['CharacterID'])
			return redirect( '/tables/'+ str(newTableEntry.id));
	
	form = NewTableForm() # An unbound form
	return render(request, 'createTable.html', {'form': form})
	
	

users/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from .models import User, UserStats
from .forms import UserForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

from esi.esi import esi_secure, esi_security, esi_verify

# get the profile
@login_required()
def profile(request):
	args = {}
	#args['UserStats'] = get_object_or_404(UserStats, user=request.user)
	return render_to_response('profile.html', args)

# user login
def user_login(request):
	return HttpResponseRedirect(esi_secure)

# user oauth
def oauth(request):
	code = request.GET.get('code')
	token = esi_security.auth(code)
	request.session['token'] = token
	request.session['char'] = esi_verify()

	user = User.objects.filter(character_id=request.session['char']['CharacterID']).first()

	if user is None:
		# Create new user
		user = User()
		user.character_id = request.session['char']['CharacterID']
		user.character_name = request.session['char']['CharacterName']
		user_stats = UserStats(balance=59879896.56)
		user_stats.save()
		user.user_stats = user_stats
		user.save()

	request.session['userinfo'] = user.getInfo()

	return HttpResponseRedirect('/tables/')

def userCleanSession(request):
	for key in request.session.keys():
		del request.session[key]

# user logout    
def user_logout(request):
	for key in request.session.keys():
		del request.session[key]
	return HttpResponseRedirect('/',{})

tables/templates/createTable.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}
<link href="{% static "assets/css/index.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<h1> Create Table</h1>

<form action="#" method="post" role="form">{% csrf_token %}
<div class="form-group row">
	<label for="id_tableLimit">Is public:</label>
	<div class="col-sm-2">	
		<select id="id_tablePublic" name="public" class="form-control mx-sm-3 mb-2">
		  <option value="True" selected>True</option> 
		  <option value="False">False</option>
		</select>
	</div>
</div>
<!--<div class="form-group row">
	<label for="id_table!Password">Password:</label>
	<div class="col-sm-2">	
		<input id="id_tablePassword" name="password" step="any" type="text" maxlength="16" value="" />
	</div>
</div>-->
<div class="form-group row">
	<label for="id_tableName">Table name:</label>
	<div class="col-sm-2">	
		<input id="id_tableName" name="name" step="any" type="text" maxlength="32" value="Keepstar's poker table" />
	</div>
</div>
<div class="form-group row">
	<label for="id_tableLimit">Table limit:</label>
	<div class="col-sm-2">	
		<input id="id_tableLimit" name="tableLimit" step="any" type="number" value="100" />
	</div>
</div>
<div class="form-group row">
	<label for="id_tableBlind">Table blind:</label>
	<div class="col-sm-2">	
		<input id="id_tableBlind" name="tableBlind" step="any" type="number" value="2" />
	</div>
</div>
<input type="submit" value="Submit" />
</form>


{% endblock %}

tables/templates/game.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static "assets/css/gameTemp.css" %}">
{% endblock %}

{% block content %}
<div class="baseContainer">
	<div class="row"> <!-- players 2-5 -->
    	<div class="large-3 columns" id="op2"><!-- Player 2 -->
        	<div class="cardContainer">
            	<div class="info">
                	<p style="display:inline"><div id="op2-name" style="display:inline">NONE</div></p>
                	<p style="display:inline">Bank: <div id="op2-bank" style="display:inline"></div></p>
                	<p style="display:inline">Bet: <div id="op2-bet" style="display:inline"></div></p>
            	</div>
            	<div class="cards">
            	    <img class="card" id="op2-card1"/>
            	    <img class="card" id="op2-card2" />
            	</div>
	        </div>
	    </div>
	    <div class="large-3 columns" id="op3"><!-- Player 3 -->
	        <div class="cardContainer">
	            <div class="info">
	                <p style="display:inline"><div id="op3-name" style="display:inline">NONE</div></p>
	                <p style="display:inline">Bank: <div id="op3-bank" style="display:inline"></div></p>
	                <p style="display:inline">Bet: <div id="op3-bet" style="display:inline"></div></p>
	            </div>
	            <div class="cards">
    	            <img class="card" id="op3-card1" />
        	        <img class="card" id="op3-card2" />
        	    </div>
        	</div>
    	</div>
   		<div class="large-3 columns" id="op4"><!-- Player 4 -->
        	<div class="cardContainer">
            	<div class="info">
                	<p style="display:inline"><div id="op4-name" style="display:inline">NONE</div></p>
                	<p style="display:inline">Bank: <div id="op4-bank" style="display:inline"></div></p>
                	<p style="display:inline">Bet: <div id="op4-bet" style="display:inline"></div></p>
            	</div>
            	<div class="cards">
            	    <img class="card" id="op4-card1" />
            	    <img class="card" id="op4-card2" />
            	</div>
        	</div>
    	</div>
    	<div class="large-3 columns" id="op5"><!-- Player 5 -->
    	    <div class="cardContainer">
    	        <div class="info">
        	        <p style="display:inline"><div id="op5-name" style="display:inline">NONE</div></p>
            	    <p style="display:inline">Bank: <div id="op5-bank" style="display:inline"></div></p>
                	<p style="display:inline">Bet: <div id="op5-bet" style="display:inline"></div></p>
            	</div>
            	<div class="cards">
            	    <img class="card" id="op5-card1" />
            	    <img class="card" id="op5-card2" />
            	</div>
        	</div>
    	</div>
	</div>
	<div class="row">
	    <div class="large-3 columns" id="op1">
	        <div class="cardContainer">
	            <div class="info">
	                <p style="display:inline"><div id="op1-name" style="display:inline">NONE</div></p>
	                <p style="display:inline">Bank: <div id="op1-bank" style="display:inline"></div></p>
	                <p style="display:inline">Bet: <div id="op1-bet" style="display:inline"></div></p>
	            </div>
	            <div class="cards">
	                <img class="card" id="op1-card1" />
	                <img class="card" id="op1-card2" />
	            </div>
	        </div>
	    </div>
	    <div class="large-6 columns">
	        <div class="cardContainer" id="tableCards">
	            <div class="tableInfo">
	                <p style="display:inline" >Pot: <div style="display:inline" id="potContainer">0</div></p>
	            </div>
	            <img class="card" id="card1" />
	            <img class="card" id="card2" />
	            <img class="card" id="card3" />
	            <img class="card" id="card4" />
	            <img class="card" id="card5" />
	        </div>
	    </div>
	    <div class="large-3 columns" id="op6">
	        <div class="cardContainer">
	            <div class="info">
	                <p style="display:inline"><div id="op6-name" style="display:inline">NONE</div></p>
	                <p style="display:inline">Bank: <div id="op6-bank" style="display:inline"></div></p>
	                <p style="display:inline">Bet: <div id="op6-bet" style="display:inline"></div></p>
	            </div>
	            <div class="cards">
	                <img class="card" id="op6-card1" />
	                <img class="card" id="op6-card2" />
	            </div>
	        </div>
	    </div>
	</div>
	<div class="row">
	    <div class="large-3 columns">
	        <div class="cardContainer" >
	            <h1>My hand:</h1>
	            <img class="card" id="myCard1" />
	            <img class="card" id="myCard2" />
	            <h2 id="betting" style="color:yellow;display:none;">Betting!</h2>
	        </div>
	    </div>
	    <div class="large-5 columns">
	        <div class="cardContainer" style="position:relative;" >
	            <button id="checkSend" class="button [tiny small large]" type="button">Check</button>
	            <button id="foldSend" class="button [tiny small large]" type="button">Fold</button>
	            <button id="startGame" class="button [tiny small large]"type="button">Start</button>
	            <p>Bank: <span id="myBank" style="color:yellow;display:inline;"></span>
	            Current Bet: <span style="display:inline" id="betContainer">0</span></p>
	            <div class="input-group" id="betBox" >
	                <input type="text" class="form-control" id="betAmt" />
	                <span class="input-group-btn">
	                    <button id="betSend" class="button [tiny small large]" type="button">Bet!</button>
	                </span>
	            </div>
	        </div>
    	</div>
    	<div class="large-4 columns">
    	    <div class="panel panel-default">
	            <div class="panel-heading">
	                <h3 class="panel-title">Chat</h3>
	            </div>
	            <div class="panel-body" id="chatBox" style="height:154px;overflow:scroll;">
	            </div>
	            <div class="panel-footer">
	                <div class="input-group">
	                    <input type="text" class="form-control" id="chatText" />
	                    <span class="input-group-btn">
	                        <button id="chatSend" class="btn btn-default" type="button">send message</button>
	                    </span>
	                </div>
	            </div>
	        </div>
	    </div>
	</div>
</div>

{% endblock %}

{% block js %}

{{ table.id }}
{{ table.currentUsers }}

<script src="http://127.0.0.1:8081/socket.io/socket.io.js"></script>
<script>
    // use this to pass variables into js from django
    var tableId    = '{{ table }}';
    var playerName = '{{ username }}';
    var moneyToUse = '{{ amountPlay}}';
    var tableLimit = '{{tableLimit}}'
    var tableBlind = '{{tableBlind}}';
</script>
<script src="{% static "assets/js/game.js" %}"></script>
<script src="{% static "assets/js/gameViewControl.js" %}"></script>
<script src="{% static "assets/js/oppPlayer.js" %}"></script>
{% endblock %}

tables/templates/tables.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}
<link href="{% static "assets/css/index.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="">
	<h1>Choose and join your table!</h1>
	<a href="newtable">Create Table</a>

	<div class="ustify-content-md-center">
		<table id="tables" class="table table-striped table-hover table-bordered">
			<thead class="thead-dark">
				<tr>
					<th scope="col" data-field="ID">ID</th>
					<th scope="col" data-field="Name">Name</th>
					<th scope="col" data-field="Public">Public</th>
					<th scope="col" data-field="Blind">Blind</th>
					<th scope="col" data-field="Limit">Limit</th>
					<th scope="col" data-field="Slots">Slots</th>
				</tr>
			</thead>
			<tbody>
				{% for table in tables %}
				<tr>
					<td>{{ table.id }}</td>
					<td>{{ table.name }}</td>
					<td>{{ table.public }}</td>
					<td>{{ table.tableBlind }}</td>
					<td>{{ table.tableLimit }}</td>
					<td>
					{% if table.currentUsers < 7 %}
					<a href="/tables/{{ table.id }}">Join {{ table.currentUsers }}/7</a>
					{% else %}
					{{ table.currentUsers }}/7
					{% endif %}
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>

{% if tables.has_other_pages %}
  <ul class="pagination">
    {% if tables.has_previous %}
      <li><a href="?page={{ tables.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in tables.paginator.page_range %}
      {% if tables.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if tables.has_next %}
      <li><a href="?page={{ tables.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}EvE Poker{% endblock %}</title>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		{% block head-css %}
		<link rel="stylesheet" type="text/css" href="{% static "assets/bootstrap/css/bootstrap.css" %}">
		<link rel="stylesheet" type="text/css" href="{% static "assets/bootstrap/css/bootstrap.min.css" %}">
		<link rel="stylesheet" type="text/css" href="{% static "assets/bootstrap/css/bootstrap.css" %}">
	    <!-- Custom styles for this template -->
	    <link href="{% static "assets/vendor/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
	    <link href="{% static "assets/vendor/magnific-popup/magnific-popup.css" %}" rel="stylesheet">
	    <link rel="stylesheet" type="text/css" href="{% static "assets/css/creative.min.css" %}">
		{% endblock %}
	</head>
		
		
	<!-- This is the start of the navigation bar at the top of the page-->
	<header>
		<nav class="navbar navbar-inverse">
		  <div class="container-fluid">
		    <div class="navbar-header">
		      <a class="navbar-brand" href="/">EvE Poker </a>
		    </div>
		    <ul class="nav navbar-nav">
		      <li><a href="/help/">Help</a></li>
		      <li><a href="/tables/">Tables</a></li>
		    </ul>
		    <ul class="nav navbar-nav navbar-right">
		    	<div id="userbar">
		    		<h4>
					{% if request.session.char %}
			      		<li>
			      			<a href="help.html"><span class="glyphicon glyphicon-plus" title="Add ISK" style="margin-right: 10px;"></span></a>
			      			<a href="/users">{{ request.session.userinfo.userstats.balance }} ISK </a>
			      			<a href="/users/logout"><span class="glyphicon glyphicon-log-out" title="Logout" style="margin-left: 10px;margin-right: 5px;"></span></a>
			      		</li>
					{% else %}
			      		<li><a href="/users/login"><span class="glyphicon glyphicon-user"></span> Login</a></li>
					{% endif %}
					</h4>
		    	</div>
		    </ul>
		  </div>
		</nav>
	</header>

	<!-- This is where you'll put your page content. Leave it blank for now. -->
	{% block content %}{% endblock %}

	<!-- This is where the footer begins -->
	<footer>
		<div class= "navbar navbar-inverse navbar-static-bottom" role="navigation">
		<div class="navbar-text pull-left">
		</div>
		<div class= "navbar-text pull-right">
		<!-- Add in your social media / github links here -->
		<a href="https://github.com/clarkdatalabs"><i class="fa fa-github-square fa-2x"></i></a>
		</div>
		<!--Below is the copyright information for the site. You can fill in your own here.-->
		<div class="navbar-text pull-left">
		&copy; Blackout Projects, 2018
		</div>
	</div>	
	</footer>

	<!--This is my javascript block. If you've included the javascript files you need in the 'static' folder then there's no need to 
	put this here and you can delete the block below.-->
	{% block head-javascript %}
    <script src="{% static "assets/vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
    <script src="{% static "assets/vendor/jquery-easing/jquery.easing.min.js" %}"></script>
    <script src="{% static "assets/vendor/scrollreveal/scrollreveal.min.j" %}s"></script>
    <script src="{% static "assets/vendor/magnific-popup/jquery.magnific-popup.min.js" %}"></script>
	<script src="{% static "assets/bootstrap/js/bootstrap.min.js" %}"></script>
	<script src="{% static "assets/bootstrap/js/bootstrap.js" %}"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	{% endblock %}
</html>

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}
<link href="{% static "assets/css/index.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}

<header class="masthead text-center text-white d-flex">
	<div class="container my-auto">
		<div class="row">
			<div class="col-lg-10 mx-auto">
			<h1 class="text-uppercase">
				<strong>Eve online poker game</strong>
			</h1>
			<hr>
			</div>
			<div class="col-lg-8 mx-auto">
			<p class="text-faded mb-5">Play your ISK and try to win against other pilots of New Eden!</p>
			<a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Find Out More</a>

				{% if esi %}
					{% autoescape off %}
						{{ esi }}
					{% endautoescape %}
				{% else %}
					<a class="btn btn-primary btn-xl js-scroll-trigger" href="/tables/">Get started</a>
				{% endif %}
			
			</div>
		</div>
	</div>
</header>

<section id="about">
	<div class="container">
	<div class="row">
		<div class="col-lg-12 text-center">
		<h2 class="section-heading">How does it work?</h2>
		<hr class="my-4">
		</div>
	</div>
	</div>
	<div class="container">
	<div class="row">
		<div class="col-lg-3 col-md-6 text-center">
		<div class="service-box mt-5 mx-auto">
			<i class="fa fa-4x fa-cubes text-primary mb-3 sr-icons"></i>
			<h3 class="mb-3">Login with Eve Online</h3>
			<p class="text-muted mb-0">Eve online ESI tool allow external application to get game informations</p>
		</div>
		</div>
		<div class="col-lg-3 col-md-6 text-center">
		<div class="service-box mt-5 mx-auto">
			<i class="fa fa-4x fa-cogs text-primary mb-3 sr-icons"></i>
			<h3 class="mb-3">Credit account</h3>
			<p class="text-muted mb-0">You can credit your account by sending ISK to a specific corporation.</p>
		</div>
		</div>
		<div class="col-lg-3 col-md-6 text-center">
		<div class="service-box mt-5 mx-auto">
			<i class="fa fa-4x fa-gamepad text-primary mb-3 sr-icons"></i>
			<h3 class="mb-3">Play games</h3>
			<p class="text-muted mb-0">Play many poker game and win ISK against other pilot of New Eden!</p>
		</div>
		</div>
		<div class="col-lg-3 col-md-6 text-center">
		<div class="service-box mt-5 mx-auto">
			<i class="fa fa-4x fa-balance-scale text-primary mb-3 sr-icons"></i>
			<h3 class="mb-3">Claim ISK</h3>
			<p class="text-muted mb-0">You can get back ISK in Eve Online by claiming them one time per week!</p>
		</div>
		</div>
	</div>
	</div>
</section>
{% endblock %}

users/templates/profile.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}
<link href="{% static "assets/css/index.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="site-wrapper-inner">

<h1>Hey  {{ user.username }}</h1>
<p>
Your Balance: {{ UserStats.balance }}
<h2>Here are some links to the other pages</h2>

<a href="/tables" class="button">Find a Table</a>
</div>

{% endblock %}